// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {}; loadServices();

module.exports = {
  src_folders: ['tests'],

  custom_commands_path:  'commands',

  webdriver: {
    start_process: true,
    server_path: 'node_modules/.bin/chromedriver',
    port: 9515,
  },

  test_settings: {
    default: {
      disable_error_log: true,

      screenshots: {
        enabled: false,
        path: 'screens',
        on_failure: true
      },

      desiredCapabilities: {
        browserName: 'chrome'
      },
    },
  },
};

function loadServices() {
  try {
    Services.chromedriver = require('chromedriver');
  } catch (err) {}
}
